### ISSUE TITLE
Unable to load OodleNetwork1UDP_State_Size from oo2net_9_win64

### ISSUE THREAD

**Issue by Wedreth** [rexlManu/la-dpsmeter#2]
After following the documentation, the docker container keeps restarting because of this error :

System.DllNotFoundException: Unable to load shared library 'oo2net_9_win64' or one of its dependencies.
at LostArkLogger.Oodle.OodleNetwork1UDP_State_Size()
   at LostArkLogger.Oodle.Init() in /app/LostArkLogger/Utilities/Oodle.cs:line 30

See the screenshot for the complete error.

![la-dpsmeter_lib-missing](https://user-images.githubusercontent.com/55022119/189832102-8875f40c-b3c6-428c-baf9-17b391da7fae.png)

**Comment by xfouloux** [comment]
same here but nothing in logs, container just don't start :/

**Comment by rexlManu** [comment]
Do you can find the oo2net_9_win64.so file on the container? But it should be included if you followed the documentation. Kinda weird.

**Comment by Wedreth** [comment]
oo2net_9_win64.so is in the app folder, ask me if you need more informations.

![image](https://user-images.githubusercontent.com/55022119/189899892-4a921a59-f402-40b8-953d-4145d1f592f2.png)

**Comment by rexlManu** [comment]
Do you run it on linux arm? Raspberry pi and such stuff? I think I have to recompile oo2net_9_win64.so with arm support.
